services:
  matchmaking_service:
    container_name: matchmaking_service
    build: .
    ports:
      - "5003:5003"
    environment:
      - DATABASE_URL=postgresql://mm_user:mm_pass@matchmaking_db:5432/matchmaking_db
      - REDIS_URL=redis://matchmaking_redis:6379/0
      - GAME_SERVICE_URL=http://host.docker.internal:5002
      - WS_GATEWAY_URL=http://host.docker.internal:5005
      - EVENT_BUS_REDIS_URL=redis://host.docker.internal:6382/0
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - matchmaking_db
      - matchmaking_redis

  matchmaking_db:
    container_name: matchmaking_db
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=mm_user
      - POSTGRES_PASSWORD=mm_pass
      - POSTGRES_DB=matchmaking_db
    ports:
      - "5435:5432"
    volumes:
      - mm_pg_data:/var/lib/postgresql/data

  matchmaking_redis:
    container_name: matchmaking_redis
    image: redis:7-alpine
    ports:
      - "6381:6379"

volumes:
  mm_pg_data:
